### ISSUE TITLE
withThemes decorator: channel.last is not a function

### ISSUE THREAD

**Issue by achendrick** [tonai/storybook-addon-themes#20]
When attempting to use the `withThemes` decorator globally I'm getting the following error:

```
channel.last is not a function
TypeError: channel.last is not a function
    at http://localhost:6006/vendors~main.df74b14a836db0724963.bundle.js:173378:29
    at mountState (http://localhost:6006/vendors~main.df74b14a836db0724963.bundle.js:142683:383)
    at Object.useState (http://localhost:6006/vendors~main.df74b14a836db0724963.bundle.js:142713:3368)
    at useState (http://localhost:6006/vendors~main.df74b14a836db0724963.bundle.js:152532:25)
    at ThemeDecorator (http://localhost:6006/vendors~main.df74b14a836db0724963.bundle.js:173377:39)
    at renderWithHooks (http://localhost:6006/vendors~main.df74b14a836db0724963.bundle.js:142620:157)
    at mountIndeterminateComponent (http://localhost:6006/vendors~main.df74b14a836db0724963.bundle.js:142894:911)
    at beginWork$1 (http://localhost:6006/vendors~main.df74b14a836db0724963.bundle.js:143197:101)
    at HTMLUnknownElement.callCallback (http://localhost:6006/vendors~main.df74b14a836db0724963.bundle.js:139868:102)
    at Object.invokeGuardedCallbackDev (http://localhost:6006/vendors~main.df74b14a836db0724963.bundle.js:139888:45)
```

I've tried using the decorator in all three use cases (global, CSF and specific story) and all three produce this same error.

I'm using storybook `5.3.13` with react.

**Comment by achendrick** [comment]
I got it sorted out.
I ran `npm i -D storybook-addon-themes` to get started (as stated in the docs).
This installs the `6.0.0-alpha.1` release in npm.

Downgrading to `5.3.0` resolves my issue.

I'd look at making `5.3.0` the "latest" release and `6.0.0-alpha.1` the "next" release.

**Comment by tonai** [comment]
Hi @achendrick, thank you for reporting.
I've changed the latest and next tag in npm.

**Comment by achendrick** [comment]
Thanks @tonai! Happy to help and love the addon 👍
